/**
  * Kiet Tran
  * ktran86
*/

#include "graphics.h"
#include "gba.h"
#include "images/f_box.h"
#include "images/f_logo.h"
#include "images/f_score_box.h"
#include "images/title_logo.h"
#include "images/f_gameover_box.h"
#include "images/f_win_box.h"
#include "images/startgame.h"

// TA-TODO: Include any header files for images generated by nin10kit.
// Example for the provided garbage image:
//#include "images/garbage.h"
// tile image array
const u16 *tiles[12] = {tile_0,tile_1,tile_2,tile_3,tile_4,tile_5,tile_6,tile_7,tile_8,tile_9,tile_10,tile_11};

// num image array
const u16 *nums[10] = {num_0,num_1,num_2,num_3,num_4,num_5,num_6,num_7,num_8,num_9};

// draw start game
void drawStartGame(void) {
    drawFullScreenImageDMA(startgame);
    waitForVBlank();

    drawCenteredString(120, 120, 2, 2, "Press START to Start Game", GREEN);
    waitForVBlank();
    drawCenteredString(120, 120, 2, 2, "Press START to Start Game", WHITE);
}

// TA-TODO: Add any draw/undraw functions for sub-elements of your app here.
// For example, for a snake game, you could have a drawSnake function
// or a drawFood function
//
// e.g.:
// static void drawSnake(Snake* snake);
// static void drawFood(Food* food);

// This function will be used to draw everything about the app
// including the background and whatnot.
void fullDrawAppState(AppState *state) {
    // TA-TODO: IMPLEMENT.

    UNUSED(state);

    //background
    fillScreenDMA(WHITE);
    waitForVBlank();

    // background tile
    drawImageDMA(0, 0, F_BOX_WIDTH, F_BOX_HEIGHT, f_box);
    // waitForVBlank();

    // logo
    drawImageDMA(0, 168, TITLE_LOGO_WIDTH, TITLE_LOGO_HEIGHT, title_logo);
    // waitForVBlank();

    // score
    drawImageDMA(35, 174, F_SCORE_BOX_WIDTH, F_SCORE_BOX_HEIGHT, f_score_box);
    // waitForVBlank();
    drawImageDMA(52, 197, NUM_0_WIDTH, NUM_0_HEIGHT, num_0);

    // instruction
    drawCenteredString(172, 78, 50, 0, "Press RESET", GRAY);
    // waitForVBlank();
    drawCenteredString(172, 88, 50, 0, "to Reset Game", GRAY);
    // waitForVBlank();

    drawCenteredString(172, 105, 55, 0, "HOW TO PLAY:", BLACK);
    // waitForVBlank();
    drawCenteredString(172, 115, 55, 0, "Use your", GRAY);
    // waitForVBlank();
    drawCenteredString(172, 125, 55, 0, "arrow keys", GRAY);
    // waitForVBlank();
    drawCenteredString(172, 135, 55, 0, "to move", GRAY);
    // waitForVBlank();
    drawCenteredString(172, 145, 55, 0, "the tiles.", GRAY);
    // waitForVBlank();

    // tile
    int index = 0;
    for (int i = 2; i < F_BOX_WIDTH; i += 39) {
        for (int j = 2; j < F_BOX_HEIGHT; j += 39) {

            if (state->blocks[index].value == 0) {
                waitForVBlank();
                drawImageDMA(i, j, TILE_0_WIDTH, TILE_0_HEIGHT, tile_0);

            } else {
                drawImageDMA(i, j, TILE_1_WIDTH, TILE_1_HEIGHT, tile_1);

            }
            index += 1;
        }
    }

}

// This function will be used to undraw (i.e. erase) things that might
// move in a frame. E.g. in a Snake game, erase the Snake, the food & the score.
void undrawAppState(AppState *state) {
    // TA-TODO: IMPLEMENT.
    fillScreenDMA(BLACK);
    UNUSED(state);
}


// This function will be used to draw things that might have moved in a frame.
// For example, in a Snake game, draw the snake, the food, the score.
void drawAppState(AppState *state) {
    // TA-TODO: IMPLEMENT.
    // UNUSED(state);
    int index = 0;
    while (index++ < 10000);
    index = 0;
    for (int i = 2; i < F_BOX_WIDTH; i += 39) {
        for (int j = 2; j < F_BOX_HEIGHT; j += 39) {
            int val = state->blocks[index].value ;
            int k = 0;
            while (val > 0 && !(val & 1)) {
                val >>= 1;
                k += 1;
            }
            drawImageDMA(i, j, 37, 37, tiles[k]);
            index += 1;
        }

    }
    int score = (state->score).totalScore;
    int len = 0;
    do {
        len += 1;
        score /= 10;
    } while (score > 0);

    score = (state->score).totalScore;
    int i = (len / 2);
    while (len-- > 0) {
        index = score % 10;
        score /= 10;
        drawImageDMA(52, (197 + (i * 5)), 6, 10, nums[index]);
        i -= 1;
    }

    index = 0;
    while (index++ < 10000);
}

// Draw Winning if the value is reached
// otherwise gameover
void drawGameOver(AppState *state) {
    delay(1000);
    if (state->score.highestValue == 2048) {
        drawFullScreenImageDMA(f_win_box);
    } else {
        drawFullScreenImageDMA(f_gameover_box);
    }
}
